version: 3

tasks:
  conftest:install:
    cmds:
    - brew install conftest
    status:
    - command -v conftest

  conftest:
    deps:
    - conftest:install 
    cmds:
    - conftest test data.yaml --policy .

  test:
    cmds:
    - opa test . -v
    - conftest verify --policy policy.rego