service:
  type: ClusterIP

ports:
  websecure:
    hostPort: 443
  web:
    hostPort: 80

# additionalArguments:
#   - --certificatesresolvers.myresolver.acme.tlschallenge
#   - --certificatesresolvers.myresolver.acme.email=foo@you.com
#   - --certificatesresolvers.myresolver.acme.storage=acme.json
#   # Please note that this is the staging Let's Encrypt server.
#   # Once you get things working, you should remove that whole line altogether.
#   - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

# Use ingressClass. Ignored if Traefik version < 2.3 / kubernetes < 1.18.x
ingressClass:
  # true is not unit-testable yet, pending https://github.com/rancher/helm-unittest/pull/12
  enabled: true
  isDefaultClass: true
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. E.g. "v1beta1"
  fallbackApiVersion: ""

# Activate Pilot integration
pilot:
  enabled: false
  token: ""
  # Toggle Pilot Dashboard
  # dashboard: false