pilot:
    token: ENC[AES256_GCM,data:inL2WveVed4AFOaLURotI56m5KbKyuVkD+vFOoxwtK0F3+4W,iv:bwRtQNHFoprdwn+7KuEJ02kbH10kIvLSPf+feQWH7ro=,tag:suTJj4kQ4a47vpjyTrLPBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hjjcpleg9ghf7tfx442c06wr3sura969eppeplwxucftq4ax9ptsyjkcu9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVzZSQXB4aHFWeWRLeUJY
            QndMQzJ1SjNOV3ZzY0N1YzBPZ3dmYmptUFV3CmdQQ3BIYTBUaEdkYXV2ZUJxTU1p
            TE1MVHVuc0d4T3VMZzFxOTgwNzZRL3cKLS0tIE5vcExjVVJDdEJnOW9FQnAvYkhH
            TzRiY0ZKUS9zSHNZdzRHNC9iUkE5bncK7/Xtv+uUeIETx/MU3EhqAZAzZDtUOjPD
            wv7OZUwXX+WNB6WsVNQlKZSVNg10kSmIbMUNFNxe7yiNwTaRZHnMUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-24T15:24:28Z"
    mac: ENC[AES256_GCM,data:z1GBGii0XpDtLNuDGvQs6SkLceLo62oMhMdMl5Y/jVsU+8HdRlbu/XMXh3Y+2MeMs4KnlGuTxXYiiIooiCAUCD59kbKBXBdT6RJeW1JwnJVKjxiyUuECJ6AzIL6xO+mfFCJYv81/M8nrwkhC1Yb+qaH4O6GxZc60vugW7HgNETE=,iv:sGIe0e9BwiOaALLeA246uSFwe2Eh04/WPMBWOkjz+68=,tag:l26xhtDqkTzTBZdEQOddlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
