---
version: "2.1"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - URL=krzwiatrzyk.eu
      - SUBDOMAINS=www
      - VALIDATION=http
      - EMAIL=krzwiatrzyk@gmail.com #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    networks:
    - proxy_network

networks:
  proxy_network:
    driver: bridge
